version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: milokhelo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=milokhelo_dev
    networks:
      - milokhelo-network

  redis:
    image: redis:7-alpine
    container_name: milokhelo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - milokhelo-network

  # Uncomment to run the app in Docker
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: milokhelo-app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - mongodb
  #     - redis
  #   networks:
  #     - milokhelo-network

volumes:
  mongodb_data:
  redis_data:

networks:
  milokhelo-network:
    driver: bridge
